trigger:
  branches:
    include:
      - 1.2

pool:
  vmImage: 'ubuntu-16.04' 

variables:
  - group: 'azure-docker-registry'
  - name: 'imageName'
    value: 'fluent/fluent-bit'
  - name: 'version'
    value: '1.2.2'

steps:
  - script: docker login -u $(docker.registry.userName) -p $(docker.registry.password) $(docker.registry.url)
    displayName: 'docker login'

  - script: >
      docker build
      -t $(docker.registry.url)/$(imageName):$(version)
      .
    displayName: 'docker build (x86)'
    enabled: false

  - script: |
      docker push $(docker.registry.url)/$(imageName):$(version)
    displayName: 'docker push (x86)'
    enabled: false

  - script: >
      docker build
      -t $(docker.registry.url)/$(imageName):$(version)-arm32v7
      -f Dockerfile-arm32v7
      .
    displayName: 'docker build (arm32v7)'

  - script: |
      docker push $(docker.registry.url)/$(imageName):$(version)-arm32v7
    displayName: 'docker push (arm32v7)'
